module.exports = {
    USER_CONNECTED: "USER_CONNECTED",
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    MESSAGE_SENT: "MESSAGE_SENT",
    MESSAGE_VIEWED: "MESSAGE_VIEWED",
    PICKUP_REQUEST_CHECK: "PICKUP_REQUEST_CHECK",
    PICKUP_REQUEST_REJECTED: "PICKUP_REQUEST_REJECTED",
    PICKUP_CONSENT_REQUEST: "PICKUP_CONSENT_REQUEST",
    PICKUP_CONSENT_RESPONSE: "PICKUP_CONSENT_RESPONSE",
    LOGOUT: "LOGOUT",
}